version: "3.11"
services:
  laravel:
    build:
      context: ./laravel-server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - server:/var/www/html
    networks:
      - app-network
    environment:
      - DB_CONNECTION=sqlite
  nuxt:
    build:
      context: ./nuxt-frontend
      dockerfile: Dockerfile
    volumes:
      - app:/app
    ports:
      - "3000:3000"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge

volumes:
  app:
  server: