services:
  laravel-api:
    build:
      context: ./laravel-server
      dockerfile: Dockerfile
    ports:
      - "8000"
    volumes:
      - server:/var/www/html
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    networks:
      - app-network
    environment:
      - DB_CONNECTION=sqlite # when .env file isn't present, it sets database to sqlite
  nuxt-app:
    build:
      context: ./nuxt-frontend
      dockerfile: Dockerfile
    volumes:
      - app:/app
    environment:
      - NUXT_HOST=0.0.0.0
      - NUXT_PORT=3000
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    networks:
      - app-network
  nginx:
    image: nginx:alpine
    ports:
    - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - nuxt-app
      - laravel-api
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
volumes:
  app:
  server: